[package]
name = "what-colour-is-it"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
js-sys = "0.3"
gloo = "0.8"
wasm-bindgen = "0.2"
gloo-timers =  {version = "0.2.6", features = ["futures"]}
wasm-bindgen-futures = "0.4.34"
chrono = "0.4"
